export default {
    APP_NAME: 'Footprints Collective.',
    slogan: 'Empowering Community-based Climate action',
    summary: 'Be part of the Solution, not the Pollution',

    Footprint: 'https://firebasestorage.googleapis.com/v0/b/footprint-collective.appspot.com/o/Branding%2Flouisa-potter-0YaUgdjZ7-Y-unsplash.jpg?alt=media&token=57742821-9e10-4a04-8204-5812ceb2604f',

    footprintSummary: 'Our carbon footprint calculator is your key to sustainability. Whether its your business, event, or personal lifestyle, we assess your impact across consumption, energy use, waste, and mobility habits.With just a few clicks, we calculate your carbon footprint, providing valuable insights into your environmental impact.Take the first step towards a greener future – measure, understand, and reduce your carbon footprint today.',
    PIC: 'https://firebasestorage.googleapis.com/v0/b/footprint-collective.appspot.com/o/Branding%2Flogo.png?alt=media&token=5545da2a-dfa7-4864-9ce5-18ec9086f317',
    AVATAR: 'https://firebasestorage.googleapis.com/v0/b/footprint-collective.appspot.com/o/Branding%2Fjohnwick.jpg?alt=media&token=3bbc6340-04cf-496c-9464-b0be8e2cc426',
    COVER: 'https://firebasestorage.googleapis.com/v0/b/footprint-collective.appspot.com/o/Branding%2Fjohn-o-nolan-uMWPrcRsrto-unsplash.jpg?alt=media&token=9989bc0c-f24e-4040-9ac1-13fccf7c14b0',
    NFT_SMART_CONTRACT: '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174',
    DAO_SMART_CONTRACT: '0x874069Fa1Eb16D44d622F2e0Ca25eeA172369bC1',

    users: 'USERS',
    activities: 'ACTIVITIES',
    communities: 'COMMUNITIES',
    footprints: 'FOOTPRINTS',
    offsets: 'OFFSETS',
    certificates: 'CERTIFICATES',

    nfts: [
        { 
            id: 0,
            pic: 'https://firebasestorage.googleapis.com/v0/b/footprint-collective.appspot.com/o/Branding%2Fhans-isaacson-e5nitFQhHcg-unsplash.jpg?alt=media&token=0db4c864-e9df-42c3-807d-fabccad87106',
            title: 'Nairobi DAO x ReFi',
            summary: 'Moors for the Future Partnership monitored the carbon footprint of the MoorLIFE2020 project, with the aim of identifying where carbon savings can be made.',
            link: 'https://firebasestorage.googleapis.com/v0/b/footprint-collective.appspot.com/o/Branding%2FCarbon-Audit-Update-Report_MoorLIFE-2020_2022.pdf?alt=media&token=d29fe555-1ea7-4a6e-9fbc-d8ecc6e48dee',
            credit: '20,000',
            timestamp: '1694008259519',
            community_id: '',
            owner: '',
            value: '200',
        },
        {
            id: 1,
            pic: 'https://firebasestorage.googleapis.com/v0/b/footprint-collective.appspot.com/o/Branding%2Fhans-isaacson-e5nitFQhHcg-unsplash.jpg?alt=media&token=0db4c864-e9df-42c3-807d-fabccad87106',
            title: 'Nairobi DAO x ReFi',
            summary: 'Moors for the Future Partnership monitored the carbon footprint of the MoorLIFE2020 project, with the aim of identifying where carbon savings can be made.',
            link: 'https://firebasestorage.googleapis.com/v0/b/footprint-collective.appspot.com/o/Branding%2FCarbon-Audit-Update-Report_MoorLIFE-2020_2022.pdf?alt=media&token=d29fe555-1ea7-4a6e-9fbc-d8ecc6e48dee',
            credit: '20,000',
            timestamp: '1694008259519',
            community_id: '',
            owner: '',
            value: '200',
        },
        {
            id: 2,
            pic: 'https://firebasestorage.googleapis.com/v0/b/footprint-collective.appspot.com/o/Branding%2Fhans-isaacson-e5nitFQhHcg-unsplash.jpg?alt=media&token=0db4c864-e9df-42c3-807d-fabccad87106',
            title: 'Nairobi DAO x ReFi',
            summary: 'Moors for the Future Partnership monitored the carbon footprint of the MoorLIFE2020 project, with the aim of identifying where carbon savings can be made.',
            link: 'https://firebasestorage.googleapis.com/v0/b/footprint-collective.appspot.com/o/Branding%2FCarbon-Audit-Update-Report_MoorLIFE-2020_2022.pdf?alt=media&token=d29fe555-1ea7-4a6e-9fbc-d8ecc6e48dee',
            credit: '20,000',
            timestamp: '1694008259519',
            community_id: '',
            owner: '',
            value: '200',
        },
        {
            id: 3,
            pic: 'https://firebasestorage.googleapis.com/v0/b/footprint-collective.appspot.com/o/Branding%2Fhans-isaacson-e5nitFQhHcg-unsplash.jpg?alt=media&token=0db4c864-e9df-42c3-807d-fabccad87106',
            title: 'Nairobi DAO x ReFi',
            summary: 'Moors for the Future Partnership monitored the carbon footprint of the MoorLIFE2020 project, with the aim of identifying where carbon savings can be made.',
            link: 'https://firebasestorage.googleapis.com/v0/b/footprint-collective.appspot.com/o/Branding%2FCarbon-Audit-Update-Report_MoorLIFE-2020_2022.pdf?alt=media&token=d29fe555-1ea7-4a6e-9fbc-d8ecc6e48dee',
            credit: '20,000',
            timestamp: '1694008259519',
            community_id: '',
            owner: '',
            value: '200',
        },
        {
            id: 4,
            pic: 'https://firebasestorage.googleapis.com/v0/b/footprint-collective.appspot.com/o/Branding%2Fhans-isaacson-e5nitFQhHcg-unsplash.jpg?alt=media&token=0db4c864-e9df-42c3-807d-fabccad87106',
            title: 'Nairobi DAO x ReFi',
            summary: 'Moors for the Future Partnership monitored the carbon footprint of the MoorLIFE2020 project, with the aim of identifying where carbon savings can be made.',
            link: 'https://firebasestorage.googleapis.com/v0/b/footprint-collective.appspot.com/o/Branding%2FCarbon-Audit-Update-Report_MoorLIFE-2020_2022.pdf?alt=media&token=d29fe555-1ea7-4a6e-9fbc-d8ecc6e48dee',
            credit: '20,000',
            timestamp: '1694008259519',
            community_id: '',
            owner: '',
            value: '200',
        },
        {
            id: 5,
            pic: 'https://firebasestorage.googleapis.com/v0/b/footprint-collective.appspot.com/o/Branding%2Fhans-isaacson-e5nitFQhHcg-unsplash.jpg?alt=media&token=0db4c864-e9df-42c3-807d-fabccad87106',
            title: 'Nairobi DAO x ReFi',
            summary: 'Moors for the Future Partnership monitored the carbon footprint of the MoorLIFE2020 project, with the aim of identifying where carbon savings can be made.',
            link: 'https://firebasestorage.googleapis.com/v0/b/footprint-collective.appspot.com/o/Branding%2FCarbon-Audit-Update-Report_MoorLIFE-2020_2022.pdf?alt=media&token=d29fe555-1ea7-4a6e-9fbc-d8ecc6e48dee',
            credit: '20,000',
            timestamp: '1694008259519',
            community_id: '',
            owner: '',
            value: '200',
        },
    ],

    countryData: [
        { label: 'Ghana', value: 'Ghana' },
    ],

    members: [
        { 
            id: 0, 
            pic: 'https://firebasestorage.googleapis.com/v0/b/footprint-collective.appspot.com/o/Branding%2Fjohnwick.jpg?alt=media&token=3bbc6340-04cf-496c-9464-b0be8e2cc426',
            title: 'Allan Okoth',
            role: 'Admin',
            address: 'allanokothdev.near',
            join_timestamp: '1694008259519',
            footprint: '30',
            offsets: '500',
        },
        {
            id: 1,
            pic: 'https://firebasestorage.googleapis.com/v0/b/footprint-collective.appspot.com/o/Branding%2Fjohnwick.jpg?alt=media&token=3bbc6340-04cf-496c-9464-b0be8e2cc426',
            title: 'Allan Okoth',
            role: 'Admin',
            address: 'allanokothdev.near',
            join_timestamp: '1694008259519',
            footprint: '30',
            offsets: '500',
        },
    ],

    categories: ["Regeneration","Recycling", 'Upcycling', 'Electric Vehicles','Waste Management', 'Solar', 'Wind Energy', 'Smart Lighting', 'Repair', 'Hybrid Cars', 'Vegetarian Dishes', 'Carbon Capture', 'Reforestation', 'Smart Access Management', 'Clean Energy', 'Community Water Systems', 'Carbon Credits'],

    activities: [
        { 
            id: 0, 
            pic: 'https://firebasestorage.googleapis.com/v0/b/footprint-collective.appspot.com/o/Branding%2Fjohn-o-nolan-uMWPrcRsrto-unsplash.jpg?alt=media&token=9989bc0c-f24e-4040-9ac1-13fccf7c14b0',
            title: ' Nairobi River Cleanup',
            summary: 'Our carbon footprint calculator is your key to sustainability. Whether its your business, event, or personal lifestyle, we assess your impact across consumption, energy use, waste, and mobility habits.With just a few clicks, we calculate your carbon footprint, providing valuable insights into your environmental impact.Take the first step towards a greener future – measure, understand, and reduce your carbon footprint today.',
            timestamp: '1694008259519',
            time: '7 PM',
            budget: 4000,
            category: 'Recycling',
            location: 'Nairobi, Kenya',
            communityTitle: 'Nairobi x ReFi community',
            community_id: 'nairobiDao',
            publisher_id: 'jamesDao',
            status: 'Complete',
            offset: 40000,
            comments: 23,
            upvotes: 23,
            downvotes: 34,
            tags: ['Recycling','Nairobi','jamesDao','nairobiDao']
        },
        {
            id: 1,
            pic: 'https://firebasestorage.googleapis.com/v0/b/footprint-collective.appspot.com/o/Branding%2Fjohn-o-nolan-uMWPrcRsrto-unsplash.jpg?alt=media&token=9989bc0c-f24e-4040-9ac1-13fccf7c14b0',
            title: ' Nairobi River Cleanup',
            summary: 'Our carbon footprint calculator is your key to sustainability. Whether its your business, event, or personal lifestyle, we assess your impact across consumption, energy use, waste, and mobility habits.With just a few clicks, we calculate your carbon footprint, providing valuable insights into your environmental impact.Take the first step towards a greener future – measure, understand, and reduce your carbon footprint today.',
            timestamp: '1694008259519',
            time: '7 PM',
            budget: 4000,
            category: 'Recycling',
            location: 'Nairobi, Kenya',
            communityTitle: 'Nairobi x ReFi community',
            community_id: 'nairobiDao',
            publisher_id: 'jamesDao',
            status: 'Complete',
            offset: 40000,
            comments: 23,
            upvotes: 23,
            downvotes: 34,
            tags: ['Recycling', 'Nairobi', 'jamesDao', 'nairobiDao']
        },
        {
            id: 2,
            pic: 'https://firebasestorage.googleapis.com/v0/b/footprint-collective.appspot.com/o/Branding%2Fjohn-o-nolan-uMWPrcRsrto-unsplash.jpg?alt=media&token=9989bc0c-f24e-4040-9ac1-13fccf7c14b0',
            title: ' Nairobi River Cleanup',
            summary: 'Our carbon footprint calculator is your key to sustainability. Whether its your business, event, or personal lifestyle, we assess your impact across consumption, energy use, waste, and mobility habits.With just a few clicks, we calculate your carbon footprint, providing valuable insights into your environmental impact.Take the first step towards a greener future – measure, understand, and reduce your carbon footprint today.',
            timestamp: '1694008259519',
            time: '7 PM',
            budget: 4000,
            category: 'Recycling',
            location: 'Nairobi, Kenya',
            communityTitle: 'Nairobi x ReFi community',
            community_id: 'nairobiDao',
            publisher_id: 'jamesDao',
            status: 'Complete',
            offset: 40000,
            comments: 23,
            upvotes: 23,
            downvotes: 34,
            tags: ['Recycling', 'Nairobi', 'jamesDao', 'nairobiDao']
        },
        {
            id: 3,
            pic: 'https://firebasestorage.googleapis.com/v0/b/footprint-collective.appspot.com/o/Branding%2Fjohn-o-nolan-uMWPrcRsrto-unsplash.jpg?alt=media&token=9989bc0c-f24e-4040-9ac1-13fccf7c14b0',
            title: ' Nairobi River Cleanup',
            summary: 'Our carbon footprint calculator is your key to sustainability. Whether its your business, event, or personal lifestyle, we assess your impact across consumption, energy use, waste, and mobility habits.With just a few clicks, we calculate your carbon footprint, providing valuable insights into your environmental impact.Take the first step towards a greener future – measure, understand, and reduce your carbon footprint today.',
            timestamp: '1694008259519',
            time: '7 PM',
            budget: 4000,
            category: 'Recycling',
            location: 'Nairobi, Kenya',
            communityTitle: 'Nairobi x ReFi community',
            community_id: 'nairobiDao',
            publisher_id: 'jamesDao',
            status: 'Complete',
            offset: 40000,
            comments: 23,
            upvotes: 23,
            downvotes: 34,
            tags: ['Recycling', 'Nairobi', 'jamesDao', 'nairobiDao']
        },
        {
            id: 4,
            pic: 'https://firebasestorage.googleapis.com/v0/b/footprint-collective.appspot.com/o/Branding%2Fjohn-o-nolan-uMWPrcRsrto-unsplash.jpg?alt=media&token=9989bc0c-f24e-4040-9ac1-13fccf7c14b0',
            title: ' Nairobi River Cleanup',
            summary: 'Our carbon footprint calculator is your key to sustainability. Whether its your business, event, or personal lifestyle, we assess your impact across consumption, energy use, waste, and mobility habits.With just a few clicks, we calculate your carbon footprint, providing valuable insights into your environmental impact.Take the first step towards a greener future – measure, understand, and reduce your carbon footprint today.',
            timestamp: '1694008259519',
            time: '7 PM',
            budget: 4000,
            category: 'Recycling',
            location: 'Nairobi, Kenya',
            communityTitle: 'Nairobi x ReFi community',
            community_id: 'nairobiDao',
            publisher_id: 'jamesDao',
            status: 'Complete',
            offset: 40000,
            comments: 23,
            upvotes: 23,
            downvotes: 34,
            tags: ['Recycling', 'Nairobi', 'jamesDao', 'nairobiDao']
        },
    ],

    history: [
        {
            id: 1,
            owner: 'allanokothdev',
            title: 'Business',
            summary: 'Footprint Collective Inc',
            startDate: 1694008259519,
            endDate: 1694008259519,
            timestamp: 1694008259519,
            location: 'Nairobi, Kenya',
            totalFootprint: 160,
            consumption: 70,
            energy: 50,
            travel: 30,
            food: 10,
            tags: ["Africa","Kenya","allanokothdev"]
        },
        {
            id: 2,
            owner: 'allanokothdev',
            title: 'Business',
            summary: 'Footprint Collective Inc',
            startDate: 1694008259519,
            endDate: 1694008259519,
            timestamp: 1694008259519,
            location: 'Nairobi, Kenya',
            totalFootprint: 160,
            consumption: 70,
            energy: 50,
            travel: 30,
            food: 10,
            tags: ["Africa", "Kenya", "allanokothdev"]
        },
        {
            id: 3,
            owner: 'allanokothdev',
            title: 'Business',
            summary: 'Footprint Collective Inc',
            startDate: 1694008259519,
            endDate: 1694008259519,
            timestamp: 1694008259519,
            location: 'Nairobi, Kenya',
            totalFootprint: 160,
            consumption: 70,
            energy: 50,
            travel: 30,
            food: 10,
            tags: ["Africa", "Kenya", "allanokothdev"]
        },
        {
            id: 4,
            owner: 'allanokothdev',
            title: 'Business',
            summary: 'Footprint Collective Inc',
            startDate: 1694008259519,
            endDate: 1694008259519,
            timestamp: 1694008259519,
            location: 'Nairobi, Kenya',
            totalFootprint: 160,
            consumption: 70,
            energy: 50,
            travel: 30,
            food: 10,
            tags: ["Africa", "Kenya", "allanokothdev"]
        },
        {
            id: 5,
            owner: 'allanokothdev',
            title: 'Business',
            summary: 'Footprint Collective Inc',
            startDate: 1694008259519,
            endDate: 1694008259519,
            timestamp: 1694008259519,
            location: 'Nairobi, Kenya',
            totalFootprint: 160,
            consumption: 70,
            energy: 50,
            travel: 30,
            food: 10,
            tags: ["Africa", "Kenya", "allanokothdev"]
        },
    ],

    notifications: [
        {
            id: '0',
            author: 'James Doe',
            action: 'join_community',
            title: ' joined ',
            summary: 'joined',
            timestamp: '29 August 2012 - 2300hr',
            community: 'Nairobi x ReFi community',
            community_id: 'nairobirefi.near',
            publisher_id: 'james.near',
        },
        {
            id: '1',
            author: 'James Doe',
            action: 'join_community',
            title: ' joined ',
            summary: 'joined',
            timestamp: '29 August 2012 - 2300hr',
            community: 'Kigali x ReFi community',
            community_id: 'kigalidev.near',
            publisher_id: 'jamesdoe.near',
        },
        {
            id: '2',
            author: 'James Doe',
            action: 'join_community',
            title: ' joined ',
            summary: 'joined',
            timestamp: '29 August 2012 - 2300hr',
            community: 'Kigali x ReFi community',
            community_id: 'kigalidev.near',
            publisher_id: 'jamesdoe.near',
        },
        {
            id: '3',
            author: 'James Doe',
            action: 'join_community',
            title: ' joined ',
            summary: 'joined',
            timestamp: '29 August 2012 - 2300hr',
            community: 'Kigali x ReFi community',
            community_id: 'kigalidev.near',
            publisher_id: 'jamesdoe.near',
        },
        {
            id: '4',
            author: 'James Doe',
            action: 'join_community',
            title: ' joined ',
            summary: 'joined',
            timestamp: '29 August 2012 - 2300hr',
            community: 'Kigali x ReFi community',
            community_id: 'kigalidev.near',
            publisher_id: 'jamesdoe.near',
        },
        {
            id: '5',
            author: 'James Doe',
            action: 'join_community',
            title: ' joined ',
            summary: 'joined',
            timestamp: '29 August 2012 - 2300hr',
            community: 'Kigali x ReFi community',
            community_id: 'kigalidev.near',
            publisher_id: 'jamesdoe.near',
        },
        {
            id: '6',
            author: 'James Doe',
            action: 'join_community',
            title: ' joined ',
            summary: 'joined',
            timestamp: '29 August 2012 - 2300hr',
            community: 'Kigali x ReFi community',
            community_id: 'kigalidev.near',
            publisher_id: 'jamesdoe.near',
        },
        {
            id: '7',
            author: 'James Doe',
            action: 'join_community',
            title: ' joined ',
            summary: 'joined',
            timestamp: '29 August 2012 - 2300hr',
            community: 'Kigali x ReFi community',
            community_id: 'kigalidev.near',
            publisher_id: 'jamesdoe.near',
        },
        {
            id: '8',
            author: 'James Doe',
            action: 'join_community',
            title: ' joined ',
            summary: 'joined',
            timestamp: '29 August 2012 - 2300hr',
            community: 'Kigali x ReFi community',
            community_id: 'kigalidev.near',
            publisher_id: 'jamesdoe.near',
        },
        {
            id: '9',
            author: 'James Doe',
            action: 'join_community',
            title: ' joined ',
            summary: 'joined',
            timestamp: '29 August 2012 - 2300hr',
            community: 'Kigali x ReFi community',
            community_id: 'kigalidev.near',
            publisher_id: 'jamesdoe.near',
        },
        {
            id: '10',
            author: 'James Doe',
            action: 'join_community',
            title: ' joined ',
            summary: 'joined',
            timestamp: '29 August 2012 - 2300hr',
            community: 'Kigali x ReFi community',
            community_id: 'kigalidev.near',
            publisher_id: 'jamesdoe.near',
        },
    ],

    comments: [
        {
            id: 0,
            title: 'Upvote',
            summary: 'Our carbon footprint calculator is your key to sustainability. Whether its your business, event, or personal lifestyle, we assess your impact across consumption, energy use, waste, and mobility habits.With just a few clicks, we calculate your carbon footprint, providing valuable insights into your environmental impact.Take the first step towards a greener future – measure, understand, and reduce your carbon footprint today.',
            link: '',
            timestamp: 1694008259519,
            author: 'Allan',
            authorPic: 'https://firebasestorage.googleapis.com/v0/b/footprint-collective.appspot.com/o/Branding%2Flogo.png?alt=media&token=5545da2a-dfa7-4864-9ce5-18ec9086f317',
            tags: ['postID','Author'],
        },
        {
            id: 1,
            title: 'Upvote',
            summary: 'Our carbon footprint calculator is your key to sustainability. Whether its your business, event, or personal lifestyle, we assess your impact across consumption, energy use, waste, and mobility habits.With just a few clicks, we calculate your carbon footprint, providing valuable insights into your environmental impact.Take the first step towards a greener future – measure, understand, and reduce your carbon footprint today.',
            link: '',
            timestamp: 1694008259519,
            author: 'Allan',
            authorPic: 'https://firebasestorage.googleapis.com/v0/b/footprint-collective.appspot.com/o/Branding%2Flogo.png?alt=media&token=5545da2a-dfa7-4864-9ce5-18ec9086f317',
            tags: ['postID', 'Author'],
        },
        {
            id: 2,
            title: 'Upvote',
            summary: 'Our carbon footprint calculator is your key to sustainability. Whether its your business, event, or personal lifestyle, we assess your impact across consumption, energy use, waste, and mobility habits.With just a few clicks, we calculate your carbon footprint, providing valuable insights into your environmental impact.Take the first step towards a greener future – measure, understand, and reduce your carbon footprint today.',
            link: '',
            timestamp: 1694008259519,
            author: 'Allan',
            authorPic: 'https://firebasestorage.googleapis.com/v0/b/footprint-collective.appspot.com/o/Branding%2Flogo.png?alt=media&token=5545da2a-dfa7-4864-9ce5-18ec9086f317',
            tags: ['postID', 'Author'],
        },
    ],

    communities: [
        { 
            id: 1,
            pic: 'https://images.pexels.com/photos/4381392/pexels-photo-4381392.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
            title: 'Ol Kalou Wetlands Regeneration ',
            summary: 'The Ol Kalou Wetlands Regeneration project covers 3 acres, projected to sequester 2 metric tons of carbon annually, fostering ecosystem restoration and carbon offsetting',
            admin: 'allanokothdev.near',
            category: 'Regeneration',
            type: 'Community',
            createdDate: 1694008259519,
            webLink: 'https://www.sustainability.org/marketplace',
            location: 'Nairobi, Kenya',
            members: '200',
            totalActivities: 4,
            auditedActivities: 5,
            tags: ['Regeneration'],
        },
        {
            id: 2,
            pic: 'https://images.pexels.com/photos/4381392/pexels-photo-4381392.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
            title: 'Ol Kalou Wetlands Regeneration ',
            summary: 'The Ol Kalou Wetlands Regeneration project covers 3 acres, projected to sequester 2 metric tons of carbon annually, fostering ecosystem restoration and carbon offsetting',
            admin: 'allanokothdev.near',
            category: 'Regeneration',
            type: 'Community',
            webLink: 'https://www.sustainability.org/marketplace',
            location: 'Nairobi, Kenya',
            members: '200',
            totalActivities: 4,
            auditedActivities: 5,
            tags: ['Regeneration', 'Upcycling'],
        },
        {
            id: 3,
            pic: 'https://images.pexels.com/photos/4381392/pexels-photo-4381392.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
            title: 'Ol Kalou Wetlands Regeneration ',
            summary: 'The Ol Kalou Wetlands Regeneration project covers 3 acres, projected to sequester 2 metric tons of carbon annually, fostering ecosystem restoration and carbon offsetting',
            admin: 'allanokothdev.near',
            category: 'Regeneration',
            type: 'Community',
            webLink: 'https://www.sustainability.org/marketplace',
            location: 'Nairobi, Kenya',
            members: '200',
            totalActivities: 4,
            auditedActivities: 5,
            tags: ['Recycling', 'Regeneration'],
        },
        {
            id: 4,
            pic: 'https://images.pexels.com/photos/4381392/pexels-photo-4381392.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
            title: 'Ol Kalou Wetlands Regeneration ',
            summary: 'The Ol Kalou Wetlands Regeneration project covers 3 acres, projected to sequester 2 metric tons of carbon annually, fostering ecosystem restoration and carbon offsetting',
            admin: 'allanokothdev.near',
            category: 'Recycling',
            type: 'Community',
            webLink: 'https://www.sustainability.org/marketplace',
            location: 'Nairobi, Kenya',
            members: '200',
            totalActivities: 4,
            auditedActivities: 5,
            tags: ['Recycling', 'Regeneration'],
        },
        {
            id: 5,
            pic: 'https://images.pexels.com/photos/4381392/pexels-photo-4381392.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
            title: 'Ol Kalou Wetlands Regeneration ',
            summary: 'The Ol Kalou Wetlands Regeneration project covers 3 acres, projected to sequester 2 metric tons of carbon annually, fostering ecosystem restoration and carbon offsetting',
            admin: 'allanokothdev.near',
            category: 'Recycling',
            type: 'Community',
            webLink: 'https://www.sustainability.org/marketplace',
            location: 'Nairobi, Kenya',
            members: '200',
            totalActivities: 4,
            auditedActivities: 5,
            tags: ['Recycling', 'Upcycling'],
        },
    ],

    onboarding: [
        { 
            id: 1,
            title: 'Join Footprint and List Your Project Today', 
            summary: 'Start your journey to making a positive impact on the planet. By listing a project on Footprint, you are joining a network of changemakers dedicated to driving sustainable change and inspiring others to take climate action.',
            text: 'Create Project Now',
            color: '',
            link: './createProject',
        },
        {
            id: 2,
            title: 'Buy Carbon Credits from Verified Projects on Footprint',
            summary: 'Get verified carbon credits from trusted projects at Footprint. It is an easy way to help the environment by buying these special credits.When you purchase, you are supporting projects that do good for the planet. Make a real difference with each credit you buy',
            text: 'Explore Projects',
            color: '',
            link: './projects',
        },
        {
            id: 3,
            title: 'Join Footprints Today and Measure Your Impact',
            summary: 'Whether you are an individual, a business, or an event organizer, Footprint empowers you to calculate your carbon footprint and take steps towards a more sustainable future. By understanding your impact, you can make informed decisions that contribute to a healthier planet. Join us on Footprint and start measuring your carbon footprint now.',
            text: 'Calculate your Footprint',
            color: '',
            link: './calculator',
        },
        {
            id: 4,
            title: 'Join Footprint and Offset Your Impact',
            summary: 'Footprint empowers individuals, businesses, and event organizers to take meaningful actions to offset their carbon footprints. By participating in verified carbon offset projects, you are making a tangible contribution to combating climate change.Join us on Footprint and be a part of the movement for a greener and more sustainable future.',
            text: 'Offset today',
            color: '',
            link: './offsets',
        },
    ],

    stepNavbar: [
        {
            id: 1,
            stepNo: '1',
            title: 'STEP 1',
            message: 'FOOD',
            state: ''
        },
        {
            id: 2,
            stepNo: '2',
            title: 'STEP 2',
            message: 'TRAVEL',
            state: ''
        },
        {
            id: 3,
            stepNo: '3',
            title: 'STEP 3',
            message: 'HOME',
            state: ''
        },
        {
            id: 4,
            stepNo: '4',
            title: 'STEP 4',
            message: 'STUFF',
            state: ''
        },

    ] 

}